version: '3.1'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - .qdrant_data:/data

volumes:
  qdrant_data:
    driver: local
